language: ruby
bundler_args: --without production
rvm:
  - 2.0.0
  - 2.1.2
env:
  - DB=sqlite
  - DB=postgresql
before_script:
  - psql -c 'create database scriba_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rspec spec
